#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envorbit')
envorbitlib = envorbit.Clone()
package = envorbitlib['PACKAGE']
project = 'orbitLib'
envorbitlib['PROJECT'] = project
install = envorbitlib['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
Export('envorbitlib')
initFile = '__init__.py'
if not os.path.exists(initFile):
	fout = open(initFile,"w")
	fout.write("#!/usr/bin/env python")
	fout.close()
listFiles = ['CalcSchHeightVel.py',initFile]
envorbitlib.Install(install,listFiles)
envorbitlib.Alias('install',install)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir = envorbitlib['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/src')
