#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2014 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os
Import('envParsers')
envRDF = envParsers.Clone()
package = os.path.join(envParsers['PACKAGE'], 'rdf')
envRDF['PACKAGE'] = package
Export('envRDF')

install = os.path.join(envParsers['PRJ_SCONS_INSTALL'], package )
initFile = '__init__.py'

listFiles = ['__init__.py', 'eRDF.py', 'iRDF.py', 'parse.py', 'read.py', 
             'uRDF.py', 'utils.py']
envRDF.Install(install,listFiles)
envRDF.Alias('install',install)

SConscript(os.path.join('reserved', 'SConscript'))
SConscript(os.path.join('language', 'SConscript'))
SConscript(os.path.join('data', 'SConscript'))
SConscript(os.path.join('units', 'SConscript'))


