#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2012 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envUtil')
install = envUtil['PRJ_LIB_DIR'] 
#envUtil.AppendUnique(LINKFLAGS = '-i4')
envUtil.AppendUnique(CPPDEFINES = ['HAVE_CONFIG_H','HAVE_FFTW=1'])
listFiles = ['args_roi.F','besseldiffs.F','bilinear.F','cfft1d_jpl.F','cfft2d.F','cffts.F', \
             'convert_sch_to_xyz.F','convert_schdot_to_xyzdot.F','cross.F','curvature.F', \
             'derampc.F','dop.F','dot.F','enubasis.F','fc.F','fourn.F','fournnr.F', \
             'getangs.F','gettcn_tcvec.F','hunt.F','inter_motion.F','interp.F','intpcoefnorm.F', \
             'latlon.F','lfit.F','lincomb.F','lookvec.F','matmat.F','matvec.F','norm.F', \
             'orrmread1.F','polint.F','radar_to_xyz.F','schbasis.F','svd.F','svdvecfit.F', \
             'svdvecfit9.F','tranmat.F','unitvec.F','utmtoll.F','zbrent.F','PowerOfTwo.cc', \
             'fftw3stub.c','io.c','second.c','fortranUtils.f90','intp_coef.f90','linalg.f90', \
             'lsq.f90','quadfit.f90','uniform_interp.f90','akima_reg.F']
lib = envUtil.Library(target = 'utilLib', source = listFiles)
envUtil.Install(install,lib)
envUtil.Alias('install',install)
