#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2013 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Piyush Agram
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envdemUtils')
envcorrectGeoid = envdemUtils.Clone()
package = envcorrectGeoid['PACKAGE']
project = 'correct_geoid_i2_srtm'
envcorrectGeoid['PROJECT'] = project
install = envcorrectGeoid['PRJ_SCONS_INSTALL'] +'/' + package 

listFiles = ['Correct_geoid_i2_srtm.py', 'egm96geoid.dat']
envcorrectGeoid.Install(install,listFiles)
envcorrectGeoid.Alias('install',install)
Export('envcorrectGeoid')
bindingsScons="bindings/SConscript"
SConscript(bindingsScons, variant_dir = envcorrectGeoid['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/bindings')
includeScons = 'include/SConscript'
SConscript(includeScons)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir=envcorrectGeoid['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/src')
