#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2014 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os
Import('envRDF')
envLanguage = envRDF.Clone()
package = os.path.join(envRDF['PACKAGE'], 'language')
envLanguage['PACKAGE'] = package
Export('envLanguage')

install = os.path.join(envRDF['PRJ_SCONS_INSTALL'], package )

listFiles = ['__init__.py', 'errors.py']

envLanguage.Install(install, listFiles)
envLanguage.Alias('install', install)

SConscript(os.path.join('grammar', 'SConscript'))
SConscript(os.path.join('lexis', 'SConscript'))


