#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os

Import('envisceobj')
envImageFilter = envisceobj.Clone()
project = 'ImageFilter'
envImageFilter['PROJECT'] = project
package = envImageFilter['PACKAGE']
Export('envImageFilter')
install = os.path.join(envImageFilter['PRJ_SCONS_INSTALL'], package, project)

listFiles = ['__init__.py', 'ImageFilter.py', 'FilterFactory.py',
    'BandExtractor.py', 'ComplexExtractor.py']

envImageFilter.Install(install,listFiles)
envImageFilter.Alias('install',install)

includeScons = os.path.join('include', 'SConscript')
SConscript(includeScons)

bindingsScons = os.path.join('bindings', 'SConscript')
SConscript(bindingsScons, variant_dir = os.path.join(
    envImageFilter['PRJ_SCONS_BUILD'], package, project, 'bindings'))

srcScons = os.path.join('src', 'SConscript')
SConscript(srcScons, variant_dir = os.path.join(
    envImageFilter['PRJ_SCONS_BUILD'], package, project, 'src'))
