#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2009 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Authors: Giangi Sacco, Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




#!/usr/bin/env python

import os

Import('env')
package = 'defaults'
envdefaults = env.Clone()
envdefaults['PACKAGE'] = package
install = os.path.join(envdefaults['PRJ_SCONS_INSTALL'], package)

listFiles = ['__init__.py']
envdefaults.Install(install,listFiles)
envdefaults.Alias('install',install)

if not 'DEFAULTS_SCONS_INSTALL' in envdefaults:
    envdefaults['DEFAULTS_SCONS_INSTALL']  = envdefaults['PRJ_SCONS_INSTALL']

Export('envdefaults')

logging = os.path.join('logging', 'SConscript')
SConscript(logging)
plugins= os.path.join('plugins', 'SConscript')
SConscript(plugins)
