#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#                                  Giangi Sacco
#                        NASA Jet Propulsion Laboratory
#                      California Institute of Technology
#                        (C) 2009  All Rights Reserved
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#!/usr/bin/env python
import os

Import('envisceobj')
envDoppler = envisceobj.Clone()
package = envisceobj['PACKAGE']
project = 'Doppler'
envDoppler['PROJECT'] = project
install = os.path.join(envisceobj['PRJ_SCONS_INSTALL'],package,project)
listFiles = ['CskSlcDopp.py','TsxDopp.py','Doppler.py','__init__.py','Calc_dop.py','DefaultDopp.py']
envisceobj.Install(install,listFiles)
envisceobj.Alias('install',install)
Export('envDoppler')
bindingsScons = 'bindings/SConscript'
SConscript(bindingsScons,variant_dir = envDoppler['PRJ_SCONS_BUILD'] + '/' + package + '/'  + project + '/bindings')
includeScons = 'include/SConscript'
SConscript(includeScons)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir = envDoppler['PRJ_SCONS_BUILD'] + '/' + package + '/'  + project + '/src')
