#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envformslclib')
build = envformslclib['PRJ_LIB_DIR'] 
envformslclib.AppendUnique(FORTRANFLAGS =  '-fopenmp')
envformslclib.AppendUnique(F90FLAGS =  '-fopenmp')
#io.c temporary #removed
listFiles = ['arraymodule.f90','mocomp.f90','rciq.f90','rcov.f90','rmpatch.f90','get_frate.f90','io.c','tsxmocompIsce.f90']
lib = envformslclib.Library(target = 'formslcLib', source = listFiles)
envformslclib.Install(build,lib)
envformslclib.Alias('build',build)
