#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envisceobj')
envOrbit = envisceobj.Clone()
package = envisceobj['PACKAGE']
project = 'Orbit'
Export('envOrbit')

srcScons = os.path.join('src','SConscript')
varDir = os.path.join(envOrbit['PRJ_SCONS_BUILD'],package,project,'src')
SConscript(srcScons, variant_dir = varDir)

install = os.path.join(envisceobj['PRJ_SCONS_INSTALL'],package,project)
listFiles = ['PDS.py','PRC.py','ODR.py','Orbit.py','OrbitExtender.py','Spice.py', '__init__.py']
envisceobj.Install(install,listFiles)
envisceobj.Alias('install',install)


SConscript(os.path.join('db', 'SConscript'))
