#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envstdproc')
package = 'alosreformat'
envalosreformat = envstdproc.Clone()
envalosreformat['PACKAGE'] = os.path.join(envstdproc['PACKAGE'],package)

install = os.path.join(envstdproc['PRJ_SCONS_INSTALL'],envalosreformat['PACKAGE'])
initFile = '__init__.py'
listFiles = [initFile]
envalosreformat.Install(install,listFiles)
envalosreformat.Alias('install',install)
Export('envalosreformat')

#do the include first sicnce it adds the CPPPATH to envalosreformat and re-exports it so the others can share it
ALOS_include = os.path.join('include','SConscript')
SConscript(ALOS_include)

ALOS_lib = os.path.join('ALOS_lib','SConscript')
SConscript(ALOS_lib)

ALOS_fbs2fbd = os.path.join('ALOS_fbs2fbd','SConscript')
SConscript(ALOS_fbs2fbd)

ALOS_fbd2fbs = os.path.join('ALOS_fbd2fbs','SConscript')
SConscript(ALOS_fbd2fbs)

