#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envALOS_fbs2fbd')
package = envALOS_fbs2fbd['PACKAGE']
project = envALOS_fbs2fbd['PROJECT']
build = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_BUILD'], package, project,
    'include')
envALOS_fbs2fbd.AppendUnique(CPPPATH = [build])
listFiles = ['ALOS_fbs2fbdmodule.h','ALOS_fbs2fbdmoduleFortTrans.h']
envALOS_fbs2fbd.Install(build,listFiles)
envALOS_fbs2fbd.Alias('build',build)
