#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envALOS_fbd2fbs')
package = envALOS_fbd2fbs['PACKAGE']
project = envALOS_fbd2fbs['PROJECT']
install = os.path.join(envALOS_fbd2fbs['PRJ_SCONS_INSTALL'], package, project)
build = os.path.join(envALOS_fbd2fbs['PRJ_SCONS_BUILD'], package, project)
libList = ['utilLib','ALOSStd','fftw3f']
envALOS_fbd2fbs.PrependUnique(LIBS = libList)
module = envALOS_fbd2fbs.LoadableModule(target = 'ALOS_fbd2fbs.abi3.so',
    source = 'ALOS_fbd2fbsmodule.c')
envALOS_fbd2fbs.Install(install,module)
envALOS_fbd2fbs.Alias('install',install)
envALOS_fbd2fbs.Install(build,module)
envALOS_fbd2fbs.Alias('build',build)
