#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envzenith2los')
package = envzenith2los['PACKAGE']
project = envzenith2los['PROJECT']
install = envzenith2los['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envzenith2los['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['gomp','zenith2los','DataAccessor','InterleavedAccessor']
envzenith2los.PrependUnique(LIBS = libList)
module = envzenith2los.LoadableModule(target = 'zenith2los.abi3.so', source = 'zenith2losmodule.cpp') 
envzenith2los.Install(install,module)
envzenith2los.Alias('install',install)
envzenith2los.Install(build,module)
envzenith2los.Alias('build',build)
