#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2011 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envissi')
envissiISSI = envissi.Clone()
project = 'ISSI'
envissiISSI['PROJECT'] = project
package = envissiISSI['PACKAGE']
build = os.path.join(envissiISSI['PRJ_SCONS_BUILD'],package,project)
install = os.path.join(envissiISSI['PRJ_SCONS_INSTALL'],package,project)
Export('envissiISSI')

includeScons = os.path.join('include','SConscript')
SConscript(includeScons)
srcScons = os.path.join('src','SConscript')
SConscript(srcScons,variant_dir = os.path.join(build ,'src'))

listFiles = ['FR.py','__init__.py']
envissiISSI.Install(install,listFiles)
envissiISSI.Alias('install',install)
