#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envImageApi')
envDataAccessor = envImageApi.Clone() 
project = 'DataAccessor'
envDataAccessor['PROJECT'] = project
package = envDataAccessor['PACKAGE']
Export('envDataAccessor')

includeScons = os.path.join('include','SConscript')
SConscript(includeScons)

bindingsScons = os.path.join('bindings','SConscript')
bindingsVarDir = os.path.join(envDataAccessor['PRJ_SCONS_BUILD'],package,project,'bindings')
SConscript(bindingsScons, variant_dir = bindingsVarDir)

srcScons = os.path.join('src','SConscript')
srcVarDir = os.path.join(envDataAccessor['PRJ_SCONS_BUILD'],package,project,'src')
SConscript(srcScons, variant_dir = srcVarDir)

install = os.path.join(envDataAccessor['PRJ_SCONS_INSTALL'],package)
listFiles = ['DataAccessorPy.py']
envDataAccessor.Install(install,listFiles)
envDataAccessor.Alias('install',install)

