#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envalosreformat')
envALOS_fbs2fbd = envalosreformat.Clone()
package = envALOS_fbs2fbd['PACKAGE']
project = 'ALOS_fbs2fbd'
envALOS_fbs2fbd['PROJECT'] = project
Export('envALOS_fbs2fbd')

bindingsScons = os.path.join('bindings','SConscript')
bindingsVarDir = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_BUILD'],package,project,'bindings')
SConscript(bindingsScons,variant_dir = bindingsVarDir)

includeScons = os.path.join('include','SConscript')
SConscript(includeScons)

install = os.path.join(envALOS_fbs2fbd['PRJ_SCONS_INSTALL'],package,project)
initFile = '__init__.py'
listFiles = ['ALOS_fbs2fbdPy.py',initFile]
envALOS_fbs2fbd.Install(install,listFiles)
envALOS_fbs2fbd.Alias('install',install)

