#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envmocompbaseline')
package = envmocompbaseline['PACKAGE']
envmocompbaseline.AppendUnique(envmocompbaseline['PRJ_LIB_DIR'])
install = envmocompbaseline['PRJ_SCONS_INSTALL'] + '/' + package
build = envmocompbaseline['PRJ_SCONS_BUILD'] + '/' + package
libList = ['mocompbaseline','orbitLib','StdOEL']
envmocompbaseline.PrependUnique(LIBS = libList)
module = envmocompbaseline.LoadableModule(target = 'mocompbaseline.abi3.so', source = 'mocompbaselinemodule.cpp') 
envmocompbaseline.Install(install,module)
envmocompbaseline.Alias('install',install)
envmocompbaseline.Install(build,module)
envmocompbaseline.Alias('build',build)
