#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Authors: Piyush Agram, Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envgetpeg')
package = envgetpeg['PACKAGE']
install = envgetpeg['PRJ_SCONS_INSTALL'] + '/' + package 
build = envgetpeg['PRJ_SCONS_BUILD'] + '/' + package 
libList = ['getpeg','orbitLib','StdOEL']
envgetpeg.PrependUnique(LIBS = libList)
module = envgetpeg.LoadableModule(target = 'getpeg.abi3.so', source = 'getpegmodule.cpp') 
envgetpeg.Install(install,module)
envgetpeg.Alias('install',install)
envgetpeg.Install(build,module)
envgetpeg.Alias('build',build)
