#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2013 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Piyush Agram
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




import os

Import('envdemUtils')
envupsampleDem = envdemUtils.Clone()
package = envupsampleDem['PACKAGE']
project = 'upsampledem'
envupsampleDem['PROJECT'] = project
install = envupsampleDem['PRJ_SCONS_INSTALL'] +'/' + package 
listFiles = ['UpsampleDem.py']
envupsampleDem.Install(install,listFiles)
envupsampleDem.Alias('install',install)
Export('envupsampleDem')
bindingsScons="bindings/SConscript"
SConscript(bindingsScons, variant_dir = envupsampleDem['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/bindings')
includeScons = 'include/SConscript'
SConscript(includeScons)
srcScons = 'src/SConscript'
SConscript(srcScons,variant_dir=envupsampleDem['PRJ_SCONS_BUILD'] + '/' + package + '/' + project + '/src')
