#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envorbitlib')
build = envorbitlib['PRJ_LIB_DIR'] 
listFiles = ['ave_tpsch.f90','unitvec.f90','dot.f90','get_tpsch.f90','latlon.F', 'geo_hdg.F', 'radar_to_xyz.F', 'convert_sch_to_xyz.F', 'convert_schdot_to_xyzdot.F', 'lincomb.F', 'matvec.F', 'schbasis.F', 'matmat.F', 'tranmat.F', 'curvature.F']
lib = envorbitlib.Library(target = 'orbitLib', source = listFiles)
envorbitlib.Install(build,lib)
envorbitlib.Alias('build',build)
