#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envicu')
install = envicu['PRJ_LIB_DIR'] 
listFiles = ['icu.F','icuState.F','icuSetState.F','abs_phase.F','bermuda.F','gen_neutrons.F','grass.F','intf_cc.F','intf_filt.F','lowpass.F','norm_cor.F','ph_sigma.F','ph_slope.F','psfilt_sub.F','residues.F','rt.F','std_cor.F','unw_rt.F']
lib = envicu.Library(target = 'icu', source = listFiles)
envicu.Install(install,lib)
envicu.Alias('install',install)
