#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envorbit')
envsch2orbit = envorbit.Clone()
package = envsch2orbit['PACKAGE']
project = 'sch2orbit'
envsch2orbit['PROJECT'] = project
Export('envsch2orbit')

bindingsScons = os.path.join('bindings','SConscript')
bindingsVarDir = os.path.join(envsch2orbit['PRJ_SCONS_BUILD'],package,project,'bindings')
SConscript(bindingsScons,variant_dir = bindingsVarDir)

includeScons = os.path.join('include','SConscript')
SConscript(includeScons)

srcScons = os.path.join('src','SConscript')
srcVarDir = os.path.join(envsch2orbit['PRJ_SCONS_BUILD'],package,project,'src')
SConscript(srcScons,variant_dir = srcVarDir)

install = os.path.join(envsch2orbit['PRJ_SCONS_INSTALL'],package)
listFiles = ['Sch2orbit.py']
envsch2orbit.Install(install,listFiles)
envsch2orbit.Alias('install',install)

