#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2011 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Eric Gurrola
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envcontrib')
envmdx = envcontrib.Clone()

OPTIMIZATION = ''
envmdx.Replace(FORTRANFLAGS = str(envmdx['FORTRANFLAGS']).replace(str(envmdx['COMPILER_OPTIMIZATION']),OPTIMIZATION).split())
envmdx.Replace(CCFLAGS = str(envmdx['CCFLAGS']).replace(str(envmdx['COMPILER_OPTIMIZATION']),OPTIMIZATION).split())

envmdx['PACKAGE'] = envcontrib['PACKAGE']
envmdx['INSTALL_COMPS'] = envcontrib['INSTALL_COMPS']
envmdx['INSTALL_APPS'] = envcontrib['INSTALL_APPS']
package = envmdx['PACKAGE']
project = 'mdx'
build = os.path.join(envmdx['PRJ_SCONS_BUILD'],package,project)
envmdx['PROJECT'] = project
Export('envmdx')

src = os.path.join('src','SConscript')
SConscript(src,variant_dir=os.path.join(build,'src'))
