#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2010 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Walter Szeliga
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#!/usr/bin/env python

import os
import fnmatch

Import('envSensordb')
envSensordbRS = envSensordb.Clone()
package = 'radarsat'
envSensordbRS['PACKAGE'] = package

listFiles = []
for root,dirs,files in os.walk(os.getcwd()):
        for file in files:
                if (fnmatch.fnmatch(file,'*.xml')):
                        listFiles.append(os.path.join(root,file))

install = os.path.join(envSensordb['SENSORDB_SCONS_INSTALL'], package)
envSensordbRS.Install(install,listFiles)
envSensordbRS.Alias('install',install)
Export('envSensordbRS')
