#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2013 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Piyush Agram
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envestamb')
package = envestamb['PACKAGE']
project = envestamb['PROJECT']
install = envestamb['PRJ_SCONS_INSTALL'] + '/' + package + '/' + project
build = envestamb['PRJ_SCONS_BUILD'] + '/' + package + '/' + project
libList = ['gomp','estambSoi','formslcLib','utilLib','fftw3f','DataAccessor','InterleavedAccessor','StdOEL']
envestamb.PrependUnique(LIBS = libList)
module = envestamb.LoadableModule(target = 'estamb.abi3.so', source = 'estambmodule.cpp') 
envestamb.Install(install,module)
envestamb.Alias('install',install)
envestamb.Install(build,module)
envestamb.Alias('build',build)
