#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright: 2012 to the present, California Institute of Technology.
# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
# Any commercial use must be negotiated with the Office of Technology Transfer
# at the California Institute of Technology.
# 
# This software may be subject to U.S. export control laws. By accepting this
# software, the user agrees to comply with all applicable U.S. export laws and
# regulations. User has the responsibility to obtain export licenses,  or other
# export authority as may be required before exporting such information to
# foreign countries or providing access to foreign persons.
# 
# Installation and use of this software is restricted by a license agreement
# between the licensee and the California Institute of Technology. It is the
# User's responsibility to abide by the terms of the license agreement.
#
# Author: Giangi Sacco
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os

Import('envEstimateOffsets')
package = envEstimateOffsets['PACKAGE']
project = envEstimateOffsets['PROJECT']
install = envEstimateOffsets['PRJ_SCONS_INSTALL'] + '/' + package 
build = envEstimateOffsets['PRJ_SCONS_BUILD'] + '/' + package 
libList = ['estimateoffsets','DataAccessor','InterleavedAccessor','utilLib','fftw3f']
envEstimateOffsets.PrependUnique(LIBS = libList)
module = envEstimateOffsets.LoadableModule(target = 'estimateoffsets.abi3.so', source = 'estimateoffsetsmodule.cpp') 
envEstimateOffsets.Install(install,module)
envEstimateOffsets.Alias('install',install)
envEstimateOffsets.Install(build,module)
envEstimateOffsets.Alias('build',build)
